### ISSUE TITLE
Android - App crashes using 'react-native-expo-metamap-sdk'

### ISSUE THREAD

**Issue by bombillazo** [GetMetaMap/metamap-reactnative-plugin#72]
Hello.

Using the `react-native-expo-metamap-sdk` package in our Expo project causes out Android application to crash. Immediately upon opening the application on an Android device or emulator, the app crashes. We don't even get to see the Splash screen. Use `adb logcat` we are able to get the following logs:

```sh
ActivityManager: Start proc 10428:com.app.android.alpha/u0a88 for activity com.app.android.alpha/.MainActivity
gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 17973248
EGL_emulation: eglMakeCurrent: 0x766ae3e6c0: ver 3 0 (tinfo 0x766ae0db20)
EGL_emulation: eglMakeCurrent: 0x766af75000: ver 3 0 (tinfo 0x766ae75380)
FirebaseApp: Device unlocked: initializing all Firebase APIs for app [DEFAULT]
FirebaseCrashlytics: Initializing Firebase Crashlytics 18.2.11 for com.app.android.alpha
FirebaseInitProvider: FirebaseApp initialization successful
ReactNativeFirebaseApp: received application context.
RNFBCrashlyticsInit: isCrashlyticsCollectionEnabled via RNFBMeta: true
RNFBCrashlyticsInit: isCrashlyticsCollectionEnabled after checking crashlytics_debug_enabled: true
RNFBCrashlyticsInit: isCrashlyticsCollectionEnabled final value: true
libcrashlytics: Initializing libcrashlytics version 3.2.0
RNFBCrashlyticsInit: initialization successful
n.android.alph: Accessing hidden field Landroid/os/Trace;->TRACE_TAG_APP:J (light greylist, reflection)
n.android.alph: Accessing hidden method Landroid/os/Trace;->isTagEnabled(J)Z (light greylist, reflection)
WM-WrkMgrInitializer: Initializing WorkManager with default configuration.
libcrashlytics: Initializing native crash handling successful.
fb-UnpackingSoSource: locked dso store /data/user/0/com.app.android.alpha/lib-main
fb-UnpackingSoSource: dso store is up-to-date: /data/user/0/com.app.android.alpha/lib-main
fb-UnpackingSoSource: releasing dso store lock for /data/user/0/com.app.android.alpha/lib-main
AndroidRuntime: Shutting down VM
AndroidRuntime: FATAL EXCEPTION: main
AndroidRuntime: Process: com.app.android.alpha, PID: 10428
AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lorg/koin/dsl/ModuleKt;
AndroidRuntime: 	at expo.modules.devlauncher.koin.DevLauncherKoinAppKt.<clinit>(DevLauncherKoinApp.kt:16)
AndroidRuntime: 	at expo.modules.devlauncher.koin.DevLauncherKoinAppKt.access$getKoinAppFactory$p(DevLauncherKoinApp.kt:1)
AndroidRuntime: 	at expo.modules.devlauncher.koin.DevLauncherKoinContext.<clinit>(DevLauncherKoinApp.kt:35)
AndroidRuntime: 	at expo.modules.devlauncher.DevLauncherController$Companion.wasInitialized(DevLauncherController.kt:345)
AndroidRuntime: 	at expo.modules.devlauncher.rncompatibility.DevLauncherReactNativeHostHandler.getUseDeveloperSupport(DevLauncherReactNativeHostHandler.kt:21)
AndroidRuntime: 	at expo.modules.ReactNativeHostWrapperBase$getUseDeveloperSupport$1.invoke(ReactNativeHostWrapperBase.kt:77)
AndroidRuntime: 	at expo.modules.ReactNativeHostWrapperBase$getUseDeveloperSupport$1.invoke(ReactNativeHostWrapperBase.kt:77)
AndroidRuntime: 	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
AndroidRuntime: 	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:170)
AndroidRuntime: 	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
AndroidRuntime: 	at kotlin.sequences.SequencesKt___SequencesKt.firstOrNull(_Sequences.kt:167)
AndroidRuntime: 	at expo.modules.ReactNativeHostWrapperBase.getUseDeveloperSupport(ReactNativeHostWrapperBase.kt:78)
AndroidRuntime: 	at expo.modules.ReactNativeHostWrapperBase.createReactInstanceManager(ReactNativeHostWrapperBase.kt:25)
AndroidRuntime: 	at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:42)
AndroidRuntime: 	at com.app.android.alpha.MainApplication.onCreate(MainApplication.java:66)
AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5871)
AndroidRuntime: 	at android.app.ActivityThread.access$1100(ActivityThread.java:199)
AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6669)
AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "org.koin.dsl.ModuleKt" on path: DexPathList[[zip file "/data/app/com.app.android.alpha-ZSwKU7iir_nyGuepLBZpTg==/base.apk"],nativeLibraryDirectories=[/data/app/com.app.android.alpha-ZSwKU7iir_nyGuepLBZpTg==/lib/arm64, /data/app/com.app.android.alpha-ZSwKU7iir_nyGuepLBZpTg==/base.apk!/lib/arm64-v8a, /system/lib64]]
AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
AndroidRuntime: 	... 25 more
libcrashlytics: Initializing libcrashlytics version 3.2.0
libcrashlytics: Initializing native crash handling successful.
ActivityManager:   Force finishing activity com.app.android.alpha/.MainActivity
Process : Sending signal. PID: 10428 SIG: 9
BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
lowmemorykiller: Error writing /proc/10428/oom_score_adj; errno=22
Zygote  : Process 10428 exited due to signal (9)
ActivityManager: Process com.app.android.alpha (pid 10428) has died: vis  +99TOP
libprocessgroup: kill(-10428, 9) failed: No such process
libprocessgroup: Successfully killed process cgroup uid 10088 pid 10428 in 0ms
SurfaceFlinger: Attempting to set client state on removed layer: Splash Screen com.app.android.alpha#0
SurfaceFlinger: Attempting to destroy on removed layer: Splash Screen com.app.android.alpha#0
WindowManager: Failed looking up window callers=com.android.server.wm.WindowManagerService.windowForClientLocked:5513 com.android.server.wm.WindowManagerService.removeWindow:1642 com.android.server.wm.Session.remove:226
SurfaceFlinger: Attempting to destroy on removed layer: AppWindowToken{8153918 token=Token{a9834fb ActivityRecord{689f68a u0 com.app.android.alpha/.MainActivity t16}}}#0
```

If we remove the Metamap dependency from our project, the build works perfectly. We tried the versions of the package from `1.7.4` all the way down to `1.7.0` with no difference.

We are following the proper setup in `app.json` and the SDK seems to work in ios with no issues.

**Comment by bombillazo** [comment]
I see this in the logs:

`Caused by: java.lang.ClassNotFoundException: Didn't find class "org.koin.dsl.ModuleKt"`

Did something change in the Android native files related to Koin? This issue started around last month without ever changing this package version.

**Comment by achatikyan** [comment]
@bombillazo  
We have updated the koin version to 3.2.2 starting from 1.7.0
- io.insert-koin:koin-core:3.1.4 -> 3.2.2
- io.insert-koin:koin-android:3.1.4 -> 3.2.2

Are you using koin inside your project? if yes, which version are you using?

**Comment by bombillazo** [comment]
I'm not sure since that is all handled internally by Expo.

**Comment by bombillazo** [comment]
@achatikyan I can confirm that version 1.6.0 works as expected.

**Comment by achatikyan** [comment]
@bombillazo  
If the project is used a different version of koin, it can cause such an issue. 
But in our sample project, version 1.7.4 works fine.

**Comment by bombillazo** [comment]
What version of expo and expo dependencies are you using?

**Comment by achatikyan** [comment]
@bombillazo 
Not sure this is what you need. But anyway those are the versions we are using in example app.

```
"dependencies": {
  "expo": "~45.0.0",
  "expo-splash-screen": "~0.15.1",
  "expo-status-bar": "~1.3.0",
  "react": "17.0.2",
  "react-dom": "17.0.2",
  "react-native": "0.68.2",
  "react-native-web": "0.17.7"
},
"devDependencies": {
  "@babel/core": "^7.12.9"
}
```

**Comment by bombillazo** [comment]
We are using Expo SDK 46, the latest version

**Comment by achatikyan** [comment]
@bombillazo  
I just updated Expo SDK to the 46.0.0 version but still works as expected for me. can you share more information? maybe it's some specific integration?


```
"dependencies": {
    "expo": "^46.0.0",
    "expo-splash-screen": "~0.16.2",
    "expo-status-bar": "~1.4.0",
    "react": "18.0.0",
    "react-dom": "18.0.0",
    "react-native": "0.69.6",
    "react-native-web": "~0.18.7"
  }
```

**Comment by bombillazo** [comment]
here are the expo dependencies we use. Judging from the logs I think the issue is with `expo-dev-client`:

```
    "expo": "~46.0.16",
    "expo-asset": "~8.6.1",
    "expo-auth-session": "~3.7.1",
    "expo-build-properties": "~0.3.0",
    "expo-constants": "~13.2.4",
    "expo-dev-client": "~1.3.1",
    "expo-font": "~10.2.1",
    "expo-linear-gradient": "~11.4.0",
    "expo-linking": "~3.2.2",
    "expo-localization": "~13.1.0",
    "expo-random": "~12.3.0",
    "expo-splash-screen": "~0.16.2",
    "expo-status-bar": "~1.4.0",
    "expo-structured-headers": "2.2.1",
    "expo-updates": "~0.14.6",
    "expo-web-browser": "~11.0.0",
```

**Comment by achatikyan** [comment]
Hi @bombillazo 

We did some internal tests and found that the issue is coming from `expo-dev-client`, as you mentioned in your comment. 

The problem is that `expo-dev-client` internally uses an older `koin` version, and it causes the issue. 

`expo-dev-client` has a new version(2.0.0) which most probably is using the latest koin version internally, but for now, it is not possible to upgrade to version 2.0.0, because it requires `Gradle` version 8.0, but our plugin is using `Grade` 7.0, we don't have any near plans to upgrade to `Gradle 8.0.`
So as a solution maybe you can replace `expo-dev-client` with an alternative dependency, which is not using `koin`.

**Comment by bombillazo** [comment]
Thanks for checking. `expo-dev-client` is a commonly used Expo package for developers that need a custom development Expo client running on their devices. There really isn't an alternative for it when using Expo.

SDKv 46 uses `"expo-dev-client": "~1.3.1",`
SDKv 47 uses `"expo-dev-client": "~2.0.0",`

So seems like the problem will prop up for both Expo SDK versions.

I'm not sure if there is a way to program a check when expo-dev-client is used so the previous version of `koin` can be used. If not, devs using the `expo-dev-client` will be force-stuck using `1.6.0`. :/

**Comment by AvoSukiasyan** [comment]
hi @bombillazo. We are going to remove the koin library from our SDK. We'll do it until 1 of December and will inform you about it. I guess after that the conflict will be solved and you can use the expo-dev-client stable version.

**Comment by AvoSukiasyan** [comment]
Hello @bombillazo. We updated Expo SDK. the last version is 1.8.0. on this version, we removed the koin library. 
can you check? please 
https://www.npmjs.com/package/react-native-expo-metamap-sdk

**Comment by bombillazo** [comment]
I will check and let you know

**Comment by AvoSukiasyan** [comment]
Hello @bombillazo. did you have a chance to test the latest version?

**Comment by bombillazo** [comment]
Not yet! Will confirm when possible.
